"""empty message

Revision ID: 14599a3904df
Revises: a4652a165cdc
Create Date: 2022-05-25 00:43:49.491746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14599a3904df'
down_revision = 'a4652a165cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
