"""empty message

Revision ID: 376331dfb365
Revises: 1a2155f6dde1
Create Date: 2022-05-30 01:27:29.601356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376331dfb365'
down_revision = '1a2155f6dde1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('past_shows', sa.Text(), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows', sa.Text(), nullable=True))
    op.add_column('Artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('past_shows', sa.Text(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.Text(), nullable=True))
    op.add_column('Venue', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows_count')
    op.drop_column('Venue', 'past_shows_count')
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Artist', 'upcoming_shows_count')
    op.drop_column('Artist', 'past_shows_count')
    op.drop_column('Artist', 'upcoming_shows')
    op.drop_column('Artist', 'past_shows')
    # ### end Alembic commands ###
